CREATE TABLE PreferenceSeedGame(PreferenceSeedID INTEGER PRIMARY KEY, GameID INTEGER NOT NULL UNIQUE, PreferenceTier VARCHAR NOT NULL, ConditionalFlag BOOLEAN DEFAULT(CAST('f' AS BOOLEAN)) NOT NULL);
