-- Governed release-status assignments for GameEdition rows with NULL ReleaseDate.
-- Generated from the validated GAIAS database state.

INSERT INTO GameEditionReleaseStatus (
    GameEditionID,
    ReleaseStatus,
    StatusReason,
    StatusSource
)
VALUES
    (47, 'Announced / TBA', 'No reliable IGDB PS5 match currently available; revisit after external metadata changes', 'IGDB defer governance'),
    (72, 'Announced / TBA', 'Official PlayStation and SEGA sources confirm a PS5 release, but the release date remains TBD.', 'Official PlayStation / Publisher verification'),
    (76, 'Announced / TBA', 'Official PlayStation Store confirms the PS5 title, but the release date remains TBD.', 'Official PlayStation / Publisher verification'),
    (96, 'Announced / TBA', 'No reliable IGDB PS5 match currently available; revisit after external metadata changes', 'IGDB defer governance'),
    (243, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'Manual review'),
    (246, 'Announced / TBA', 'IGDB currently has Black Myth: Zhong Kui but no PS5 platform metadata; revisit after external metadata changes', 'IGDB defer governance'),
    (264, 'Announced / TBA', 'Reliable game identity confirmed by IGDB and RAWG, but neither source currently provides a PlayStation 5 release date.', 'IGDB + RAWG fallback validation'),
    (328, 'Unresolved', 'GAIAS lists Call of Duty 4: Modern Warfare as PS4 but IGDB identifies the original title as PS3; requires source title/platform review before matching', 'IGDB defer governance'),
    (339, 'Platform Mismatch', 'IGDB currently lists Call of Sentinels only for PC and Nintendo Switch; requires source platform review or later metadata refresh', 'IGDB defer governance'),
    (365, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (367, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (368, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (369, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (407, 'Platform Mismatch', 'IGDB currently lists Clockwork Revolution only for Xbox Series and PC; requires source platform review or later metadata refresh', 'IGDB defer governance'),
    (530, 'Unresolved', 'IGDB contains both the remake and original-classic Destroy All Humans records on PS4 and the GAIAS title does not distinguish them', 'IGDB defer governance'),
    (564, 'Edition Mismatch', 'IGDB has the base Dissidia Final Fantasy NT record but no reliable Digital Deluxe Edition record to preserve edition identity', 'IGDB defer governance'),
    (566, 'Unresolved', 'IGDB does not currently provide a reliable PS5 match for the GAIAS title Divinity', 'IGDB defer governance'),
    (572, 'Platform Mismatch', 'IGDB lists Don Bradman Cricket 14 for PS3 PC Xbox 360 and Xbox One but not PS4 so the source platform requires review', 'IGDB defer governance'),
    (602, 'Unresolved', 'IGDB does not currently return a reliable record for Dragon Quest XII The Flames of Fate', 'IGDB defer governance'),
    (614, 'Platform Mismatch', 'IGDB lists Drova Forsaken Kin for PS5 but not PS4 so the source platform requires review', 'IGDB defer governance'),
    (643, 'Unresolved', 'IGDB currently lists Earthblade only for PC so the GAIAS PS5 record requires later source review', 'IGDB defer governance'),
    (671, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (697, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'Manual review'),
    (708, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (711, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (756, 'Edition Mismatch', 'IGDB base Help Wanted record lacks PS5 while a separate Full Time Edition record exists for PS5; source edition requires review', 'IGDB defer governance'),
    (772, 'Unresolved', 'IGDB currently lists Fourteen Years of Flames only for PC; revisit after platform metadata changes', 'IGDB defer governance'),
    (791, 'Unresolved', 'IGDB currently lists Gang of Dragon only for PC; revisit after platform metadata changes', 'IGDB defer governance'),
    (798, 'Edition Mismatch', 'IGDB Gold Bundle record is Xbox One only while the base Generation Zero game supports PS4; defer to preserve edition identity', 'IGDB defer governance'),
    (810, 'Platform Mismatch', 'IGDB lists Ghostrunner II for PS5 but not PS4; source platform requires review', 'IGDB defer governance'),
    (823, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'Manual review'),
    (824, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'Manual review'),
    (827, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (871, 'Announced / TBA', 'Reliable game identity confirmed by IGDB and RAWG, but neither source currently provides a PlayStation 5 release date.', 'IGDB + RAWG fallback validation'),
    (920, 'Edition Mismatch', 'Hollow Knight Voidheart Edition does not have a distinct reliable PS5 edition record in IGDB; defer rather than collapse edition identity into the base game', 'IGDB defer governance'),
    (944, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'Manual review'),
    (996, 'Announced / TBA', 'IGDB currently identifies the announced PS5 project as Untitled John Wick Game while GAIAS uses John Wick; defer until the official title is settled', 'IGDB defer governance'),
    (999, 'Edition Mismatch', 'IGDB Employee of the Month Edition is currently represented as PS5 while GAIAS records a PS4 entitlement; source edition/platform requires review', 'IGDB defer governance'),
    (1001, 'Announced / TBA', 'Reliable game identity confirmed by IGDB and RAWG, but neither source currently provides a PlayStation 5 release date.', 'IGDB + RAWG fallback validation'),
    (1004, 'Announced / TBA', 'Reliable game identity confirmed by IGDB and RAWG, but neither source currently provides a PlayStation 5 release date.', 'IGDB + RAWG fallback validation'),
    (1022, 'Announced / TBA', 'RAWG returned 2026-12-31, which was flagged as a possible year-end placeholder rather than a confirmed platform-specific release date.', 'RAWG fallback validation'),
    (1035, 'Edition Mismatch', 'IGDB does not provide a reliable King''s Quest Complete Collection record for PS4; defer rather than collapse the collection into the base game', 'IGDB defer governance'),
    (1057, 'Edition Mismatch', 'IGDB Knights of Pen and Paper Bundle record does not include PS4 while individual titles do; defer to preserve bundle identity', 'IGDB defer governance'),
    (1108, 'Edition Mismatch', 'IGDB does not provide a reliable Light Fairytale Prologue Bundle record for PS4; defer rather than infer which episode combination the bundle represents', 'IGDB defer governance'),
    (1109, 'Unresolved', 'IGDB currently lists Light No Fire only for PC; revisit after external platform metadata changes', 'IGDB defer governance'),
    (1186, 'Edition Mismatch', 'IGDB Digital Deluxe record is currently Xbox-only while the base Martha Is Dead record supports PS4; defer to preserve edition identity', 'IGDB defer governance'),
    (1218, 'Edition Mismatch', 'IGDB currently returns Metal Gear Solid Master Collection Vol. 2 Bonus Content rather than a clear base Vol. 2 record; defer until edition structure is clearer', 'IGDB defer governance'),
    (1262, 'Platform Mismatch', 'IGDB Moss Book II is represented as a VR title without a plain PS4 platform entry; source platform/VR entitlement requires review', 'IGDB defer governance'),
    (1283, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'Manual review'),
    (1308, 'Announced / TBA', 'Official PlayStation Store confirms a PS5 release in 2027, but no exact release date is currently listed.', 'Official PlayStation / Publisher verification'),
    (1313, 'Platform Mismatch', 'IGDB Neptunia reVerse is currently PS5-only while GAIAS records PS4; source platform requires review', 'IGDB defer governance'),
    (1365, 'Announced / TBA', 'IGDB has Oceanhorn 3 Legend of the Shadow Sea but currently lists only iOS; defer PS5 source until platform metadata changes', 'IGDB defer governance'),
    (1406, 'Platform Mismatch', 'IGDB Outward 2 currently lists only PC; defer PS5 source until platform metadata changes', 'IGDB defer governance'),
    (1435, 'Announced / TBA', 'Official crowdfunding project confirms PlayStation 5 as a supported platform, but no exact release date is currently established.', 'Official Penny Blood / Double Kickstarter verification'),
    (1446, 'Announced / TBA', 'Official PlayStation Store confirms the PS5 title, but the release date remains TBD.', 'Official PlayStation / Publisher verification'),
    (1491, 'Platform Mismatch', 'IGDB Project Awakening currently lists PlayStation 4 and Xbox One but not PlayStation 5; source platform requires review', 'IGDB defer governance'),
    (1493, 'Announced / TBA', 'Project Retrograde: The Becoming is confirmed for PS5, but no release date has been announced.', 'Official / publisher verification'),
    (1494, 'Unresolved', 'No reliable IGDB record for Project S was identified; title is too generic to infer a match', 'IGDB defer governance'),
    (1495, 'Unresolved', 'IGDB Project Spectrum record currently has no platform metadata; defer until external metadata improves', 'IGDB defer governance'),
    (1515, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (1531, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (1532, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (1533, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (1534, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (1535, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (1536, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'Manual review'),
    (1537, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (1539, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'Manual review'),
    (1543, 'Unresolved', 'Ratchet and Clank Up Your Arsenal has no PS4-native IGDB record and acquisition source is Unknown; defer rather than infer PS2 or PS3 legacy lineage', 'IGDB defer governance'),
    (1544, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'Manual review'),
    (1563, 'Edition Mismatch', 'IGDB has the base Regalia game but no reliable Royal Edition OST Combo record; defer to preserve package identity', 'IGDB defer governance'),
    (1591, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (1592, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (1650, 'Unresolved', 'IGDB has distinct 2016 and 2024 PlayStation 4 Siren release lineages and GAIAS acquisition source is Unknown; defer rather than choose arbitrarily', 'IGDB defer governance'),
    (1665, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (1674, 'Platform Mismatch', 'IGDB Samson currently lists only PC and provides no reliable PlayStation 5 match; defer until platform metadata changes', 'IGDB defer governance'),
    (1685, 'Unresolved', 'No reliable IGDB match for Schedule I Drug Empire was identified and several similarly named PlayStation titles exist; defer rather than infer identity', 'IGDB defer governance'),
    (1706, 'Platform Mismatch', 'IGDB Shadow Gambit The Cursed Crew currently lists PlayStation 5 but not PlayStation 4; source platform requires review', 'IGDB defer governance'),
    (1765, 'Platform Mismatch', 'IGDB Sky Children of the Light currently lists PlayStation 4 but not PlayStation 5; source platform requires review', 'IGDB defer governance'),
    (1785, 'Edition Mismatch', 'IGDB Season Pass Edition record is Xbox-only while the base Sniper Ghost Warrior 3 supports PS4; defer to preserve edition identity', 'IGDB defer governance'),
    (1793, 'Announced / TBA', 'Son of Thanjai is confirmed for PS5 and targeted for 2027, but no exact release date is currently announced.', 'Official / publisher verification'),
    (1824, 'Announced / TBA', 'Reliable game identity confirmed by IGDB and RAWG, but neither source currently provides a PlayStation 5 release date.', 'IGDB + RAWG fallback validation'),
    (1856, 'Announced / TBA', 'Star Wars: Eclipse remains officially announced and in development, with no release date currently announced.', 'Official / publisher verification'),
    (1857, 'Announced / TBA', 'Star Wars: Fate of the Old Republic has been officially announced, but no release date is currently announced.', 'Official / publisher verification'),
    (1899, 'Platform Mismatch', 'IGDB Submersed is represented as PlayStation VR rather than PlayStation 4; source platform and VR entitlement semantics require review', 'IGDB defer governance'),
    (1934, 'Platform Mismatch', 'IGDB Supreme Experiment currently lists only PC; defer PS5 source until platform metadata changes', 'IGDB defer governance'),
    (1945, 'Announced / TBA', 'Official PlayStation Store confirms Swords of Legends for PS5, with release date to be determined.', 'Official / publisher verification'),
    (1958, 'Unresolved', 'No reliable IGDB match for TAL The Arcane Lands was identified; Arcane Lands is PC-only and title identity is uncertain', 'IGDB defer governance'),
    (1965, 'Unresolved', 'Tails of Iron 2 appears to refer to Tails of Iron II Whiskers of Winter already represented separately by GAIAS GameID 1947; defer to avoid assigning one IGDB ID to two GAIAS games', 'IGDB defer governance'),
    (1986, 'Announced / TBA', 'Reliable game identity confirmed by IGDB and RAWG, but neither source currently provides a PlayStation 5 release date.', 'IGDB + RAWG fallback validation'),
    (2030, 'Announced / TBA', 'The Cube is confirmed for PS5, but no exact release date is currently established.', 'Official / publisher verification'),
    (2039, 'Platform Mismatch', 'IGDB The Drifter currently lists PC Mac Linux and Nintendo Switch but not PlayStation 5; defer until platform metadata changes', 'IGDB defer governance'),
    (2041, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (2069, 'Edition Mismatch', 'IGDB Complete Trilogy record is Xbox One only while the three individual Van Helsing games have PS4 releases; defer to preserve bundle identity', 'IGDB defer governance'),
    (2110, 'Platform Mismatch', 'IGDB The Medium currently supports PlayStation 5 but not PlayStation 4; source platform requires review', 'IGDB defer governance'),
    (2138, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (2162, 'Unresolved', 'IGDB The Walking Dead Saints and Sinners is represented as a PlayStation VR title rather than a standard PlayStation 4 release; defer to preserve VR platform semantics', 'IGDB defer governance'),
    (2319, 'Platform Mismatch', 'IGDB Wanderstop currently lists PlayStation 5 but not PlayStation 4; source platform requires review', 'IGDB defer governance'),
    (2321, 'Unresolved', 'IGDB has two distinct War of the Monsters PlayStation 4 records representing different release lineages; defer rather than choose arbitrarily', 'IGDB defer governance'),
    (2342, 'Platform Mismatch', 'IGDB Welcome to Brightville currently lists only PC; defer PS5 source until platform metadata changes', 'IGDB defer governance'),
    (2347, 'Platform Mismatch', 'IGDB Westlanders currently lists only PC; defer PS5 source until platform metadata changes', 'IGDB defer governance'),
    (2366, 'Platform Mismatch', 'IGDB Witchbrook currently lists Xbox Nintendo and PC platforms but not PlayStation 5; defer until platform metadata changes', 'IGDB defer governance'),
    (2376, 'Announced / TBA', 'Woochi the Wayfarer is officially confirmed as a PS5 title, but no release date is currently announced.', 'Official / publisher verification'),
    (2389, 'Edition Mismatch', 'IGDB Complete Edition record does not include PlayStation 4 while the base X-Morph Defense record does; defer to preserve edition identity', 'IGDB defer governance'),
    (2391, 'Not Applicable - Cloud Streaming', 'Non-native PlayStation title accessed through PlayStation Plus cloud streaming; native PS4 release date is not applicable.', 'IGDB match governance'),
    (2448, 'Announced / TBA', 'Reliable game identity confirmed by IGDB and RAWG, but neither source currently provides a PlayStation 5 release date.', 'IGDB + RAWG fallback validation')
ON CONFLICT (GameEditionID) DO UPDATE SET
    ReleaseStatus = EXCLUDED.ReleaseStatus,
    StatusReason = EXCLUDED.StatusReason,
    StatusSource = EXCLUDED.StatusSource,
    LastReviewedAt = now();
