-- Authoritative seed/upsert for GamePlayabilityProfile.
--
-- Purpose:
--   1. Preserve the 44 pre-existing manually curated playability profiles.
--   2. Add the 56 Priority 1 playability reviews completed during
--      recommendation-engine revalidation.
--   3. Make GamePlayabilityProfile reproducible and safe to rerun.
--
-- ControlSchemeRisk vocabulary:
--   None
--   Moderate
--   High
--
-- "None" means no identified control-scheme risk under the current
-- GAIAS playability rules. It does not mean the game is universally easy.
--
-- Review signals such as IGDB Virtual Reality, Music, or Side-View Shooter
-- are used only to prioritize manual review. They do not automatically
-- determine playability-profile values.

INSERT INTO GamePlayabilityProfile (
    GameID,
    SpecialAccessoryRequired,
    ControlSchemeRisk,
    RhythmFlag,
    SHMUPFlag,
    SoulslikeFlag,
    MitigationAvailable,
    PlayabilityNotes
)
VALUES
    (28, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Peaceful exploration-focused structure with minimal combat and reflex pressure; sensitivity and axis options provide limited control mitigation.'),
    (31, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Visual novel, investigation, and puzzle-oriented gameplay create low reflex demand; forgiving structure and minimal action pressure provide mitigation.'),
    (41, FALSE, 'High', FALSE, FALSE, TRUE, TRUE, 'Deliberate melee combat emphasizes stamina management, dodging, parrying, timing, and repeated encounters; progression, combat styles, and practice provide mitigation.'),
    (44, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Virtual reality content is optional rather than required; aerial combat demands sustained spatial control, while standard controller play and difficulty options provide mitigation.'),
    (49, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Turn-based combat and exploration keep reflex demand low; progression and party management provide mitigation.'),
    (51, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Primarily exploration, puzzle-solving, and simple adventure gameplay with limited reflex demand and straightforward combat.'),
    (62, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Standard third-person action controls; generous aiming assistance and broad difficulty options provide strong mitigation.'),
    (78, FALSE, 'High', FALSE, FALSE, FALSE, FALSE, 'Legacy fixed-camera movement, tank-style controls, aiming, combat, and navigation create substantial control burden; little meaningful built-in mitigation is available.'),
    (80, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based RPG combat minimizes reflex demand; leveling, equipment, party composition, and progression provide mitigation.'),
    (85, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Top-down open-world action combines driving, aiming, combat, and pursuit sequences; progression and adjustable challenge provide mitigation.'),
    (92, FALSE, 'High', FALSE, FALSE, FALSE, TRUE,
 'Complex contextual controls, timing cues, and intentionally limited guidance create substantial control and learning burden; tutorial and interface assistance provide partial mitigation.'),
    (94, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Fast real-time action combat requires dodging, aiming, and timing; selectable difficulty provides mitigation.'),
    (95, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Fast-paced third-person action-RPG combat requires dodging, aiming, and character switching; selectable difficulty provides mitigation.'),
    (111, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Turn-based RPG structure keeps motor and reflex burden low; difficulty and progression systems provide mitigation.'),
    (113, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time action-RPG combat and party management create coordination demand; difficulty settings, character progression, and equipment provide mitigation.'),
    (117, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional third-person action-RPG controls with selectable difficulty and no identified special playability-risk category.'),
    (127, FALSE, 'Moderate', FALSE, FALSE, TRUE, TRUE,
 'Souls-like stamina-based combat and punishing encounters create elevated playability risk; AI or human companion support provides mitigation.'),
    (128, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Standard action-adventure controls with no identified accessory, rhythm, SHMUP, Souls-like, or major control-scheme concern.'),
    (129, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional Assassin''s Creed movement, stealth, combat, and sailing; upgrades, ranged tools, stealth, and alternate approaches provide mitigation.'),
    (134, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional Assassin''s Creed movement, stealth, and combat with no identified major control-risk category; upgrades and alternate approaches provide mitigation.'),
    (135, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional Assassin''s Creed movement and combat with no identified major playability-risk category.'),
    (136, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Same underlying game and control model as the duplicate Black Flag entry; no major control-risk category identified.'),
    (138, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Familiar Assassin''s Creed controls and systems with no identified major playability-risk category.'),
    (143, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional Assassin''s Creed controls; stealth, ranged tools, upgrades, and alternate approaches can reduce combat pressure.'),
    (145, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Parkour, stealth, combat, and dense crowd navigation require added coordination; upgrades, stealth, ranged tools, and co-op provide mitigation.'),
    (193, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Conventional third-person action-platforming with forgiving combat and progression; no identified major control-risk category.'),
    (199, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Side-scrolling action, stealth, combat, and traversal require timing and coordination; progression and forgiving checkpoint structure provide mitigation.'),
    (200,  FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (201, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Freeflow combat, traversal, Batmobile driving, and gadget use require coordination; difficulty options and alternate approaches provide mitigation.'),
    (202, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Freeflow combat, counters, gadgets, traversal, and predator encounters create coordination demand; difficulty settings and tactical approaches provide mitigation.'),
    (203, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person combat, stealth, traversal, counters, and camera movement create moderate coordination demand; difficulty settings and forgiving progression provide mitigation.'),
    (204, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Freeflow combat, gadgets, traversal, and predator encounters require coordination; difficulty settings and tactical approaches provide mitigation.'),
    (205, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Twin-stick action combat and frequent simultaneous movement and aiming create coordination demand; adjustable difficulty and progression provide mitigation.'),
    (209, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'First-person shooting requires sustained aiming, movement, and reaction timing; campaign difficulty settings and multiplayer role flexibility provide mitigation.'),
    (211, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'First-person shooting requires sustained aiming, movement, and reaction timing; campaign difficulty settings and class or loadout flexibility provide mitigation.'),
    (212, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'First-person shooting requires sustained aiming, movement, and reaction timing; difficulty settings and conventional shooter assists provide mitigation.'),
    (214, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Very fast action combat, dodging, combo execution, and reaction timing create substantial coordination demand; easier automatic modes and progression provide strong mitigation.'),
    (216, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Straightforward third-person action-adventure with simple combat and forgiving progression; no major playability-risk category identified.'),
    (225, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Deliberate real-time combat, navigation, survival systems, and punishing encounters create moderate burden; less-punishing exploration-focused mode provides mitigation.'),
    (234,  FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (240, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person combat combines shooting, powers, weapon switching, and environmental threats; easier difficulty and save systems provide mitigation.'),
    (245, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Twin-stick movement and aiming, aerial navigation, and combat create coordination demand; progression, upgrades, and adjustable challenge provide mitigation.'),
    (251, FALSE, 'High', FALSE, FALSE, FALSE, FALSE,
 'Legacy third-person combat and movement are comparatively stiff and timing-sensitive, with limited modern assistance and no strong mitigation identified.'),
    (263, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Legacy third-person action combat, camera movement, platforming, and targeting create moderate coordination burden; checkpoints and progression provide mitigation.'),
    (283, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Fast traversal, trick chaining, camera movement, and combat create moderate coordination demand; forgiving movement systems and progression provide mitigation.'),
    (291, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional first-person shooter controls; local or online co-op provides meaningful combat mitigation.'),
    (292, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional first-person shooter controls; optional local or online co-op provides meaningful combat mitigation.'),
    (294, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Platforming and movement can require timing and spatial coordination, but virtual reality is optional and forgiving progression provides mitigation.'),
    (295, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Real-time action-RPG combat relies on dodging, stance and weapon management, and timing; selectable difficulty and progression provide mitigation.'),
    (302, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person zero-gravity movement, survival systems, and resource management create coordination and navigation burden; difficulty and progression systems provide mitigation.'),
    (313, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Turn-based combat keeps most reflex demand low, but timed attacks and overworld platforming add input precision requirements; difficulty and assist options provide mitigation.'),
    (317,  FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (320,  FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (322, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Survival-horror combat, resource management, aiming, and enemy pressure create moderate playability burden; selectable difficulty provides mitigation.'),
    (346, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Arcade soccer combat and action sequences require timing, movement, and reaction input; difficulty options and progression provide mitigation.'),
    (365, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person melee combat, dodging, blocking, platforming, and quick-time sequences create moderate coordination demand; difficulty settings and progression provide mitigation.'),
    (366, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Third-person action combat relies on dodging, blocking, weapon switching, and boss timing; selectable difficulty provides mitigation.'),
    (368, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Simple action-RPG combat with forgiving controls, lightweight progression, and no identified major control-risk category.'),
    (369, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Simple action-RPG combat with forgiving controls, lightweight progression, and optional co-op; no major control-risk category identified.'),
    (386, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'High-speed three-dimensional space combat requires simultaneous movement, orientation, aiming, drifting, and ability management; difficulty settings and progression provide mitigation.'),
    (391, FALSE, 'Moderate', FALSE, FALSE, TRUE, TRUE,
 'Souls-like action combat is deliberate and timing-based, but selectable difficulty provides meaningful mitigation.'),
    (406, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Low-pressure exploration, driving, and narrative structure with minimal combat demand; no identified major control-risk category.'),
    (410, FALSE, 'Moderate', FALSE, FALSE, TRUE, TRUE, 'Souls-like combat emphasizes stamina, dodging, timing, and punishing encounters; AI partner support, progression, and build flexibility provide meaningful mitigation.'),
    (411, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Survival combat, crafting, inventory management, and environmental systems create layered burden; difficulty and server settings plus co-op provide strong mitigation.'),
    (413, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Virtual reality is optional rather than required; painting, traversal, and motion-oriented interaction create some control burden, while standard non-VR play provides mitigation.'),
    (416, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Fast run-and-gun combat requires sustained movement, aiming, projectile avoidance, platforming, and rapid reactions; selectable difficulty and cooperative play provide limited mitigation.'),
    (428, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Arcade racing requires sustained steering precision, drift timing, boost chaining, and rapid reactions; difficulty settings and character options provide mitigation.'),
    (470, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional action-RPG controls with pause-driven inventory systems; weapon growth, leveling, items, and preparation provide mitigation.'),
    (471, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional action-RPG combat with pause-driven menus, character switching, weapons, items, and extensive progression; grinding and equipment upgrades provide mitigation.'),
    (472, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based JRPG structure keeps reflex demand low; difficulty settings, party composition, and progression provide mitigation.'),
    (477, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time combat, dodging, aiming, and positioning create moderate coordination burden; difficulty settings, progression, and co-op provide mitigation.'),
    (479, FALSE, 'Moderate', FALSE, FALSE, TRUE, TRUE,
 'Souls-influenced dodge and timing combat creates elevated playability risk; multiple difficulty levels provide mitigation.'),
    (481,  FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (489,  FALSE, 'None', FALSE, FALSE, TRUE, TRUE,
 'Conditional A-tier: substantially more playable with mitigation.'),
    (494, FALSE, 'Moderate', FALSE, FALSE, FALSE, FALSE,
 'Legacy controls and persistent time pressure create additional playability burden; no strong built-in mitigation identified for this version.'),
    (495, FALSE, 'Moderate', FALSE, FALSE, FALSE, FALSE,
 'Legacy-era controls, inventory management, survivor management, and persistent time pressure create added burden; no strong built-in mitigation identified.'),
    (496, FALSE, 'Moderate', FALSE, FALSE, FALSE, FALSE,
 'Retains legacy-era movement, inventory pressure, survivor management, and timer-driven structure; no strong built-in mitigation identified.'),
    (497, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'More forgiving controls and reduced time-pressure emphasis than earlier Dead Rising entries; adjustable difficulty provides mitigation.'),
    (508, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Turn-based RPG structure keeps reflex demand low; difficulty and progression systems provide mitigation.'),
    (511, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Deliberate action combat, dodging, positioning, and boss encounters create moderate coordination demand; progression, upgrades, and forgiving structure provide mitigation.'),
    (524, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person shooting requires sustained aiming and movement coordination; character builds, gear progression, cooperative play, and easier activities provide mitigation.'),
    (530, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Legacy first-person movement, aiming, inventory management, and interface conventions create moderate burden; difficulty settings, tactical play, and character progression provide mitigation.'),
    (531, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person stealth and action involve layered systems and aiming demands; easier difficulty and multiple noncombat approaches provide mitigation.'),
    (532, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person stealth and action involve layered systems and aiming demands; multiple difficulty levels, stealth, hacking, and alternate routes provide strong mitigation.'),
    (533, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Fast character-action combat combines movement, camera control, dodging, weapon attacks, character-specific mechanics, and combo inputs; easier modes, progression, and automatic assistance provide strong mitigation.'),
    (534, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Fast character-action combat combines movement, camera control, dodging, weapon attacks, character-specific mechanics, and combo inputs; easier difficulty and automatic assist provide strong mitigation.'),
    (536, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting, melee combat, movement, and camera control create moderate coordination demand; difficulty settings and progression provide mitigation.'),
    (537, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time side-scrolling combat, aiming, movement, platforming, and inventory management create moderate coordination demand; progression, upgrades, and difficulty options provide mitigation.'),
    (542, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Turn-based combat minimizes reflex demand; difficulty selection, grinding, party building, and progression provide strong mitigation.'),
    (549, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Turn-based tactical structure minimizes reflex demand; extensive grinding, overleveling, and progression provide strong difficulty mitigation.'),
    (550, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'First-person stealth and action require aiming, movement, powers, and environmental awareness; granular difficulty settings and multiple noncombat approaches provide strong mitigation.'),
    (567, FALSE, 'Moderate', FALSE, FALSE, TRUE, TRUE,
 'Souls-like combat emphasizes stamina, dodging, positioning, and resource management; ranged builds, progression, and equipment optimization provide mitigation.'),
    (569, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time survival combat, movement, inventory management, and resource pressure create moderate coordination demand; preparation, crafting, and world settings provide mitigation.'),
    (585, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Standard controller layout; adjustable difficulty provides meaningful combat mitigation.'),
    (599, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Turn-based JRPG combat keeps reflex demand low; difficulty settings, party building, and progression provide mitigation.'),
    (602,  FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (616, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional action-adventure controls with adjustable difficulty and comfort options; no major playability-risk category identified.'),
    (620, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person parkour and melee combat create coordination and reaction demands; adjustable difficulty and assistance options provide mitigation.'),
    (621, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person parkour and melee combat require added coordination; difficulty options and optional co-op provide meaningful mitigation.'),
    (624, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Large-scale real-time combat can become visually and mechanically busy, but difficulty settings, character progression, and straightforward crowd-combat systems provide mitigation.'),
    (629, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Combat can be demanding, especially early, but easier difficulty settings, adjustable combat parameters, and companions provide mitigation.'),
    (632, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Virtual reality is optional rather than required; space-flight combat requires continuous aiming and movement coordination, while difficulty and configuration options provide mitigation.'),
    (633, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting and large-scale enemy encounters require sustained aiming and movement; adjustable difficulty, class selection, and progression provide mitigation.'),
    (634, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting and large-scale enemy encounters require sustained aiming and movement; adjustable difficulty and controller options provide mitigation.'),
    (635, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting and large enemy encounters require sustained aiming and movement; selectable difficulty, equipment, and progression provide mitigation.'),
    (636, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting and large enemy groups create sustained aiming and movement demands; easier difficulty and character progression provide mitigation.'),
    (651, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Straightforward third-person action-platforming with simple combat and forgiving structure; no major playability-risk category identified.'),
    (659, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Virtual reality is supported but not required; complex flight controls create moderate control burden, while standard controller play and configurable controls provide mitigation.'),
    (667, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person melee combat, platforming, traversal, and camera management create moderate coordination demand; difficulty settings and forgiving progression provide mitigation.'),
    (673, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time action combat includes dodging, parrying, timing, and positioning demands; difficulty settings and progression provide mitigation.'),
    (676, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Relaxed farming and exploration structure with simple controls and little sustained reflex pressure; no major playability-risk category identified.'),
    (677, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Third-person shooting and vehicle sections create coordination burden; controller configuration and improved sensitivity behavior provide mitigation.'),
    (680, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Low-pressure exploratory structure with minimal reaction-time demand; automatic continuation provides additional mitigation.'),
    (689, FALSE, 'High', FALSE, FALSE, FALSE, FALSE, 'High-speed racing requires sustained steering precision, rapid reactions, and narrow-margin recovery; the original game offers little meaningful mitigation.'),
    (690, FALSE, 'High', FALSE, FALSE, FALSE, FALSE, 'Extreme-speed racing requires sustained steering precision, rapid reactions, boost management, and narrow-margin recovery; little meaningful built-in mitigation is available.'),
    (691, FALSE, 'High', FALSE, FALSE, FALSE, FALSE, 'High-speed racing requires sustained steering precision, rapid reactions, boost management, and narrow-margin recovery; little meaningful built-in mitigation is available.'),
    (692, FALSE, 'High', FALSE, FALSE, FALSE, FALSE, 'High-speed racing requires sustained steering precision, rapid reactions, and narrow-margin recovery; little meaningful built-in mitigation is available.'),
    (698, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Third-person shooting and telekinetic combat can become visually and mechanically busy; aiming assistance and difficulty options provide mitigation.'),
    (700, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Survival systems and timing-based melee increase playability burden; difficulty, companion, and progression systems provide mitigation.'),
    (701, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based JRPG combat minimizes reflex demand; party building, difficulty options, and progression provide mitigation.'),
    (704,  FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (706, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Real-time combat, inventory management, and online survival systems add burden; V.A.T.S., builds, progression, and co-op provide mitigation.'),
    (707,  FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (710, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person aiming and combat create sustained coordination demand; easier difficulty, stealth, upgrades, and conventional controls provide mitigation.'),
    (711, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person shooting and traversal require sustained aiming and movement; easier difficulty, stealth, progression, and weapon upgrades provide mitigation.'),
    (712, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person shooting and traversal require sustained aiming and movement; selectable difficulty, stealth, progression, and companion options provide mitigation.'),
    (715, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person shooting and chaotic combat require sustained aiming and movement; difficulty settings, companions, stealth, and progression provide mitigation.'),
    (716, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person combat, aiming, traversal, and animal-command systems create coordination demand; difficulty settings, stealth, companions, and progression provide mitigation.'),
    (720, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person exploration, camera-based combat, aiming, movement, and tense encounters create moderate coordination demand; difficulty settings and progression provide mitigation.'),
    (724, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Fast action combat, dodging, character switching, and boss timing create coordination burden; selectable difficulty and progression provide mitigation.'),
    (731,  FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (734, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Fast real-time combat, character switching, targeting, and camera management add coordination burden; difficulty settings and party flexibility provide mitigation.'),
    (735, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based JRPG combat minimizes reflex demand; menu-driven combat, party progression, and deliberate pacing provide mitigation.'),
    (739, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'Turn-based combat minimizes reflex and control burden; no conventional difficulty setting identified for this release.'),
    (750, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Real-time brawler combat can become hectic and combo-heavy; difficulty settings, healing items, upgrades, and progression provide mitigation.'),
    (783, TRUE, 'None', FALSE, FALSE, FALSE, FALSE, 'Core gameplay relies on Wii U GamePad-specific interactions; the required platform accessory triggers exclusion under current GAIAS rules.'),
    (792, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person combat and survival systems create coordination burden; easier difficulty, cooperative play, and accessibility options provide strong mitigation.'),
    (793, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person combat, ship management, resource systems, and procedural survival create layered coordination burden; progression and difficulty tuning provide mitigation.'),
    (797, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Metroidvania combat, aiming, dodging, and boss encounters create moderate coordination demand; progression, upgrades, and accessibility or difficulty options provide mitigation.'),
    (801, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Stealth-focused exploration and light action create limited reflex demand; forgiving progression and low combat pressure provide mitigation.'),
    (809, FALSE, 'Moderate', FALSE, TRUE, FALSE, TRUE, 'Vertical scrolling shoot-em-up gameplay requires sustained movement, aiming, and projectile avoidance; difficulty and progression systems provide mitigation.'),
    (811, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Fast hunting-style combat requires camera management, dodging, guarding, and weapon coordination; AI allies, progression, and equipment provide mitigation.'),
    (812, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Fast real-time hunting combat requires camera management, dodging, guarding, and weapon-system coordination; AI allies, progression, and equipment provide mitigation.'),
    (813, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Fast real-time hunting combat requires camera, dodge, guard, and weapon-form coordination; AI companions and progression provide mitigation.'),
    (814, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Fast real-time hunting combat requires camera, dodge, guard, and weapon-form coordination; AI companions, progression, and equipment provide mitigation.'),
    (817, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time action combat, dodging, blocking, platforming, and quick-time sequences create moderate coordination demand; difficulty settings and progression provide mitigation.'),
    (818, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time action combat, dodging, blocking, platforming, and quick-time sequences create moderate coordination demand; difficulty settings and progression provide mitigation.'),
    (819, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time action combat, dodging, blocking, platforming, and quick-time sequences create moderate coordination demand; difficulty settings and progression provide mitigation.'),
    (828, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based JRPG combat minimizes reflex demand; party building, progression, and menu-driven systems provide mitigation.'),
    (829,  FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (839, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Fast action-RPG combat can be demanding; assist modes, difficulty options, remapping, and practice features provide strong mitigation.'),
    (850, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Gravity-based traversal requires simultaneous camera orientation, directional movement, aerial attacks, and spatial judgment; progression and forgiving retries provide mitigation.'),
    (861, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Relaxed exploration and life-sim structure with low combat pressure and no identified special control risk.'),
    (886, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Relaxed exploration and relationship-focused structure with relatively simple combat; difficulty options and co-op support provide mitigation.'),
    (891, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Narrative adventure structure includes frequent quick-time events, motion-oriented inputs, and timed action sequences; checkpoints and difficulty options provide mitigation.'),
    (912,  FALSE, 'None', FALSE, FALSE, TRUE, TRUE,
 'Conditional A-tier: strong preference fit when difficulty is mitigated.'),
    (917, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'First-person shooting and open-world traversal require sustained aiming and movement; difficulty settings, progression, weapons, and stealth options provide mitigation.'),
    (926, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Top-down survival combat, aiming, movement, and resource management create moderate coordination demand; progression, crafting, and difficulty options provide mitigation.'),
    (937, FALSE, 'Moderate', FALSE, FALSE, FALSE, FALSE, 'Legacy movement, camera, escort, and platforming conventions create moderate control burden; no strong built-in difficulty-assistance mechanism identified.'),
    (954, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Narrative adventure gameplay includes repeated quick-time events, timed inputs, and contextual action sequences; forgiving checkpoints provide mitigation.'),
    (958, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Fast third-person traversal, aiming, powers, and combat create coordination demand; difficulty settings and progression provide mitigation.'),
    (978, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based RPG combat keeps reflex demand low; difficulty settings, party building, and progression provide mitigation.'),
    (979,  FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (980,  FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (982,  FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (994, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Real-time brawler combat and chase or action sequences add coordination demand; difficulty settings, healing, upgrades, and combat assistance provide mitigation.'),
    (999, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Standard open-world action controls; alternate preparation and progression approaches can reduce mission pressure.'),
    (1000, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional third-person open-world controls with no identified major control-risk category.'),
    (1010, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time melee combat, dodging, positioning, and dungeon navigation create moderate coordination demand; progression and equipment systems provide mitigation.'),
    (1025, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Naval combat requires steering, positioning, speed management, broadside timing, and skill use; selectable difficulty and controller-focused design provide mitigation.'),
    (1035, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional third-person action-RPG controls with multiple difficulty settings and flexible character builds.'),
    (1058, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Investigation-focused structure has relatively limited reflex demand; driving assistance and action-sequence skipping provide mitigation.'),
    (1059, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based RPG combat keeps reflex demand low; difficulty settings, party building, and progression provide mitigation.'),
    (1066, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Low-pressure narrative and driving structure with minimal combat or reflex demand; no major playability-risk category identified.'),
    (1068, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Narrative exploration and puzzle-focused gameplay create low reflex demand; forgiving progression and minimal combat pressure provide mitigation.'),
    (1073, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting, stealth, positioning, and resource management create moderate coordination demand; difficulty settings and tactical play provide mitigation.'),
    (1075, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Legacy third-person action combat, camera movement, platforming, and targeting create moderate coordination burden; checkpoints and progression provide mitigation.'),
    (1076, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person action-platforming and combat require camera control, timing, and movement coordination; difficulty and progression systems provide mitigation.'),
    (1079, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Accessible action-adventure structure with simple combat, forgiving checkpoints, character abilities, and optional co-op.'),
    (1080, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Forgiving LEGO action-adventure controls with simple combat, frequent checkpoints, character abilities, and optional co-op.'),
    (1082, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Forgiving LEGO action-adventure structure with simple combat, exploration, frequent checkpoints, and low failure pressure.'),
    (1085, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Simple, forgiving action-adventure controls with optional co-op and low failure pressure; no major control-risk category identified.'),
    (1086, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Family-oriented action-adventure gameplay uses straightforward combat, traversal, and forgiving progression; no identified major control-risk category.'),
    (1094, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Narrative adventure structure has low general motor demand; forgiving checkpoints and limited action pressure provide mitigation.'),
    (1123, FALSE, 'Moderate', FALSE, FALSE, TRUE, TRUE,
 'Souls-like combat emphasizes stamina, dodging, blocking, and deliberate timing; co-op, builds, progression, and ranged or magic options provide mitigation.'),
    (1134, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Real-time movement and aiming combine with card-driven tactical combat; difficulty and progression systems provide mitigation.'),
    (1138, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Puzzle-platforming emphasizes deliberate movement and environmental reasoning rather than combat or rapid reflexes; no major playability-risk category identified.'),
    (1146, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'First-person parkour requires rapid camera control, chained movement inputs, spatial judgment, and precision under momentum; checkpoints and forgiving traversal systems provide mitigation.'),
    (1153, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional third-person shooting and driving controls; easier difficulty, aim assistance, and driving assists provide mitigation.'),
    (1154, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional third-person action controls with multiple combat approaches and no identified major control-risk category.'),
    (1155, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (1162, FALSE, 'High', FALSE, FALSE, FALSE, FALSE, 'Legacy stealth, camera, movement, melee combat, and execution mechanics create substantial control burden; little meaningful built-in mitigation is available.'),
    (1177, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'PlayabilityNotes: Turn-based tactical combat greatly reduces reflex demand; difficulty settings, card upgrades, party composition, and progression provide strong mitigation.'),
    (1185, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Third-person shooting, powers, movement, and squad management create coordination demand; multiple difficulty settings, aim assistance, builds, and squad support provide mitigation.'),
    (1186, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional third-person RPG and shooter controls; multiple difficulty levels provide strong mitigation.'),
    (1189, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Legacy third-person shooting, aiming, camera control, and bullet-time combat create moderate burden; difficulty settings and bullet-time provide mitigation.'),
    (1201, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Legacy fixed-camera stealth, aiming, movement, and inventory conventions create substantial control burden; modern collection conveniences and adjustable difficulty provide partial mitigation.'),
    (1202, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Legacy stealth, movement, camera, and aiming conventions create moderate control burden; adjustable difficulty and modern collection features provide mitigation.'),
    (1203, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Legacy stealth and movement conventions create moderate control burden; adjustable difficulty and modern collection features provide mitigation.'),
    (1204, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (1208, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (1212, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'First-person shooting, stealth, resource management, and tense combat create moderate coordination demand; difficulty options and slower tactical play provide mitigation.'),
    (1214, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'First-person shooting, stealth, resource management, and survival-horror pressure create coordination burden; adjustable difficulty and controller options provide mitigation.'),
    (1219, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Side-view shooter and platformer, but not a SHMUP under GAIAS rules; standard controls and easier difficulty reduce burden.'),
    (1220, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (1221, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (1234, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Deliberate action combat requires camera management, positioning, weapon-specific inputs, and monster-pattern learning; equipment, preparation, and multiplayer provide mitigation.'),
    (1236, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based monster-battling RPG combat minimizes reflex demand; party building, progression, and deliberate command selection provide mitigation.'),
    (1237, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Turn-based combat keeps reflex demand low; party building, monster selection, equipment, and progression provide substantial mitigation.'),
    (1240, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Complex real-time hunting combat requires camera control, positioning, weapon mastery, dodging, and monster-pattern recognition; gear progression, preparation, SOS multiplayer, and build flexibility provide mitigation.'),
    (1254, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Directional melee and mounted combat require coordination and practice; extensive difficulty settings substantially reduce challenge.'),
    (1259, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Investigation and exploration-focused adventure with limited combat and low reflex demand; forgiving structure provides mitigation.'),
    (1269, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Generally low-pressure crafting and life-sim structure with conventional controls; combat is not the dominant difficulty driver.'),
    (1290, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (1291, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Racing requires sustained steering and reaction input; easier difficulty and driving-assistance settings provide strong mitigation.'),
    (1292, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'High-speed arcade racing requires sustained steering and reaction input; difficulty settings and forgiving event structure provide mitigation.'),
    (1293, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Racing and pursuit sequences require sustained steering and reaction input; driving assists, progression, and vehicle upgrades provide mitigation.'),
    (1294, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Racing controls can feel sensitive and require sustained coordination; alternate Wii U control approaches provide some mitigation.'),
    (1313, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional action-RPG controls; adjustable difficulty provides meaningful combat mitigation.'),
    (1314, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (1334, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Varied minigames include motion, aiming, movement, and asymmetric-control demands; the Wii U GamePad is a standard platform controller rather than a special accessory, and forgiving minigame structure provides mitigation.'),
    (1335, FALSE, 'Moderate', FALSE, FALSE, TRUE, TRUE,
 'Souls-like stamina and stance-based combat is demanding and timing-heavy; summons, co-op, gear progression, and build optimization provide mitigation.'),
    (1336, FALSE, 'Moderate', FALSE, FALSE, TRUE, TRUE,
 'Highly demanding Souls-like combat with stance, ki, dodge, block, and Yokai systems; co-op, summons, gear progression, and builds provide mitigation.'),
    (1340, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time action combat, dodging, movement, and camera management create moderate coordination demand; difficulty options and progression provide mitigation.'),
    (1368, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time action combat, dodging, camera management, and traversal create moderate coordination demand; difficulty settings and progression provide mitigation.'),
    (1372, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Standard third-person open-world action controls; selectable difficulty provides meaningful combat mitigation.'),
    (1387, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (1412, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Exploration and investigation-focused structure with limited reflex demand; no identified major control-risk category.'),
    (1418, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'First-person movement, survival management, time pressure, and hostile encounters create moderate burden; difficulty options and deliberate pacing provide mitigation.'),
    (1420, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'First-person shooting, aiming, movement, stealth, and coordinated combat create moderate control demand; difficulty settings, builds, and cooperative play provide mitigation.'),
    (1427, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based JRPG combat minimizes reflex demand; difficulty settings, party building, and progression provide strong mitigation.'),
    (1450, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Family-oriented action gameplay uses straightforward controls and relatively forgiving challenge; no identified major control-risk category.'),
    (1454, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting, aiming, movement, and ability use create moderate coordination demand; character variety, progression, and conventional shooter assistance provide mitigation.'),
    (1455, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting and movement create sustained aiming and reaction demands; character abilities, co-op, progression, and difficulty structure provide mitigation.'),
    (1456, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Third-person action combines movement, aiming, territory-clearing, and combat under pressure; difficulty and progression systems provide mitigation.'),
    (1462, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Conventional third-person simulation controls with driving and contextual interaction; difficulty and assist settings provide mitigation, with no identified major control-risk category.'),
    (1490, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Legacy 3D platforming, combat, traversal, and camera management create moderate coordination demand; forgiving progression and checkpoints provide mitigation.'),
    (1491, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, '3D platforming, combat, traversal, and camera management create moderate coordination demand; extensive accessibility and difficulty options provide strong mitigation.'),
    (1493, FALSE, 'High', FALSE, FALSE, FALSE, FALSE, 'Boxing gameplay depends heavily on rapid reactions, pattern recognition, precise dodging, and timed attacks; little meaningful built-in mitigation is available.'),
    (1494, FALSE, 'High', FALSE, FALSE, FALSE, FALSE, 'Legacy high-speed vehicle combat and pursuit sequences demand rapid aiming, steering, and reactions; punishing difficulty and limited modern assistance create substantial unmitigated control burden.'),
    (1495, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'High-speed vehicle combat and pursuit sequences require rapid steering, aiming, and reactions; improved difficulty balance and progression provide mitigation.'),
    (1500, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time roguelike combat, aiming, dodging, and procedural encounters create moderate coordination demand; progression and repeated runs provide mitigation.'),
    (1501, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (1516, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Conventional action-platformer controls with straightforward combat and traversal; no identified major control-risk category.'),
    (1517, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional action-platformer controls; easier difficulty provides strong combat mitigation.'),
    (1518, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Conventional action-platformer combat and traversal with no identified major control-risk category; progression and straightforward controls provide mitigation.'),
    (1519, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Conventional action-platformer controls with no identified major control-risk category; adjustable control options and progression provide mitigation.'),
    (1522, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Conventional action-platformer combat and traversal with no identified major control-risk category; progression, weapons, and upgrades provide mitigation.'),
    (1523, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Conventional action-platformer shooting and traversal with forgiving structure; weapons, upgrades, and difficulty options provide mitigation.'),
    (1525, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Conventional action-platformer shooting and traversal with no identified major control-risk category; weapons, upgrades, and progression provide mitigation.'),
    (1526, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Action-platforming, camera control, combat, and traversal create moderate coordination demand; forgiving progression and upgrades provide mitigation.'),
    (1530, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Conventional action-platformer shooting and traversal with adjustable difficulty and co-op support; no identified major control-risk category.'),
    (1535, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Fast arena combat, platforming, movement, and multiplayer-style challenges create moderate coordination demand; straightforward mechanics and progression provide mitigation.'),
    (1540, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Legacy third-person shooting, aiming, and horseback combat create moderate coordination burden; difficulty settings and progression provide mitigation.'),
    (1542, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (1551, FALSE, 'Moderate', FALSE, FALSE, TRUE, TRUE,
 'Souls-like combat combines dodging, stamina management, ranged aiming, and punishing encounters; co-op, builds, gear progression, and difficulty selection provide mitigation.'),
    (1556, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Fixed camera angles and legacy-style movement create substantial control burden; alternate modern movement and easier difficulty provide mitigation.'),
    (1559, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'Resident Evil 4 is a high-A example with acceptable modern controls.'),
    (1560, TRUE, 'Moderate', FALSE, FALSE, FALSE, FALSE,
 'Wii edition requires Wii Remote and Nunchuk motion-oriented controls; special accessory requirement triggers hard exclusion under current GAIAS rules.'),
    (1561, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting, movement, inventory management, and action sequences create moderate burden; difficulty options, co-op, and progression provide mitigation.'),
    (1562, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting, movement, melee actions, quick-time sequences, and large combat encounters create moderate coordination demand; difficulty settings and co-op provide mitigation.'),
    (1564, FALSE, 'High', FALSE, FALSE, FALSE, FALSE, 'Legacy tank-style movement, fixed camera conventions, and limited aiming flexibility create substantial control burden with little built-in mitigation.'),
    (1565, FALSE, 'High', FALSE, FALSE, FALSE, TRUE,
 'Fixed camera angles and legacy-style movement create substantial control burden; alternate modern movement and easier difficulty provide mitigation.'),
    (1566, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person competitive shooting, aiming, movement, and reaction timing create moderate coordination demand; conventional shooter controls and progression provide mitigation.'),
    (1568, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person survival-horror shooting and movement create moderate burden; difficulty options and progression provide mitigation.'),
    (1569, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person survival-horror shooting, movement, and resource management create moderate burden; difficulty options and progression provide mitigation.'),
    (1570, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person survival-horror shooting, movement, and co-op-oriented combat create moderate burden; difficulty settings and progression provide mitigation.'),
    (1571, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'First-person and third-person survival-horror combat require aiming, movement, resource management, and reaction timing; virtual reality is optional, while difficulty settings and assistance options provide mitigation.'),
    (1572, FALSE, 'High', FALSE, FALSE, FALSE, FALSE,
 'Legacy tank-style movement, fixed camera angles, and limited aiming flexibility create substantial control burden with little built-in mitigation.'),
    (1573, TRUE, 'High', FALSE, FALSE, FALSE, FALSE, 'Wii release relies on Wii Remote and Nunchuk pointer-style controls for core gameplay; special accessory requirement triggers hard exclusion under current GAIAS rules.'),
    (1592, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'High-speed sports and trick inputs can demand coordination, but auto-landing, multiple control presets, remapping, backtrack, adjustable difficulty, and Zen mode provide strong mitigation.'),
    (1596, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (1599, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Action-RPG combat can be demanding, but easier difficulty provides meaningful mitigation.'),
    (1609, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional action-RPG controls with pause-driven support systems; leveling, equipment, items, and party management provide mitigation.'),
    (1616, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'High-speed skating, aiming, tricks, enemy tracking, and shooting create substantial simultaneous control demands; assist options provide meaningful mitigation.'),
    (1627, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional action-RPG and life-sim controls; easier difficulty, companions, crafting, and overleveling provide substantial mitigation.'),
    (1629, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Top-down action combat uses stamina, blocking, aiming, and dodge timing; easier difficulty and aiming assistance provide mitigation.'),
    (1632, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Exploration, cycling, photography, and narrative interaction create low reflex demand; forgiving structure and minimal combat pressure provide mitigation.'),
    (1635, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Older survival-FPS structure adds aiming, resource, and combat burden; adjustable difficulty, manual saving, and control assistance provide mitigation.'),
    (1636, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Older survival-FPS structure adds resource and combat burden; adjustable difficulty, manual saving, and control assistance provide mitigation.'),
    (1637, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Older survival-FPS structure adds resource and combat burden; adjustable difficulty, manual saving, and control assistance provide mitigation.'),
    (1642, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based RPG combat minimizes reflex demand; party construction, progression, and tactical planning provide mitigation.'),
    (1646, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Standard open-world action controls; adjustable difficulty provides meaningful mitigation.'),
    (1648, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (1667, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting, dodging, aiming, and boss encounters create coordination burden; difficulty settings and progression provide mitigation.'),
    (1684, FALSE, 'Moderate', FALSE, FALSE, FALSE, FALSE,
 'Isometric stealth and action RPG combines layered movement, stealth, combat, and traversal systems; no strong difficulty-reduction mechanism identified.'),
    (1693, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Fast first-person melee and shooting combat require sustained aiming, movement, and reaction timing; difficulty settings, upgrades, and co-op provide mitigation.'),
    (1698, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person combat, traversal, aiming, stealth, and puzzle movement create coordination demand; separate difficulty controls and accessibility options provide strong mitigation.'),
    (1706, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Puzzle-platforming and perspective-switching emphasize deliberate movement rather than sustained reflex pressure; forgiving checkpoints and low combat demand provide mitigation.'),
    (1707, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Top-down driving, shooting, and action sequences create moderate coordination demand; straightforward progression and forgiving structure provide mitigation.'),
    (1716, FALSE, 'High', FALSE, FALSE, FALSE, FALSE,
 'Legacy movement and camera controls are notably awkward, and QTE or timing-sensitive sequences add substantial control burden with little built-in mitigation.'),
    (1717, FALSE, 'High', FALSE, FALSE, FALSE, FALSE,
 'Legacy movement and camera controls remain awkward, with numerous QTE and timing-sensitive sequences and little built-in mitigation.'),
    (1719, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Investigation-focused structure with conventional movement and camera controls; combat can be de-emphasized and assistance options reduce pressure.'),
    (1720, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Investigation-focused adventure with conventional movement and camera controls and limited reflex demand.'),
    (1722, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Investigation-focused adventure with conventional movement and limited reflex pressure; action sequences are secondary and generally forgiving.'),
    (1725, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time action-RPG combat, dodging, movement, and party management create coordination demand; difficulty settings and progression provide mitigation.'),
    (1754, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Low-pressure exploration and resource-gathering structure with conventional controls; difficulty and control options provide strong mitigation.'),
    (1761, FALSE, 'Moderate', FALSE, FALSE, FALSE, FALSE, 'Survival, crafting, inventory management, and real-time combat create layered coordination and resource burden; no sufficiently strong built-in difficulty-reduction mechanism identified.'),
    (1763, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Precision aiming and stealth can require fine motor control; difficulty and aim-assistance options substantially reduce the burden.'),
    (1781, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'High-speed traversal and reaction-based combat create coordination demand; selectable difficulty and assistance settings provide mitigation.'),
    (1788, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based JRPG combat minimizes reflex demand; party building, difficulty options, and progression provide strong mitigation.'),
    (1811, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting, movement, aiming, and map awareness create moderate coordination demand; standard Wii U GamePad controls are part of the platform and do not constitute a special accessory.'),
    (1816, FALSE, 'Moderate', FALSE, TRUE, FALSE, TRUE, 'On-rails and all-range vehicle shooting requires sustained aiming, evasive movement, and reaction timing; route variation, retries, and progression through alternate paths provide some mitigation.'),
    (1818, FALSE, 'High', FALSE, TRUE, FALSE, FALSE, 'Dual-screen and gyro-heavy vehicle shooting creates substantial control burden; unusual aiming and control requirements offer limited meaningful mitigation.'),
    (1823, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Fast action-RPG combat and aerial movement add coordination burden; difficulty options and AI-controlled party support provide mitigation.'),
    (1827, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'First-person and third-person shooting require sustained aiming, movement, and reaction timing; difficulty settings, class options, and multiplayer support provide mitigation.'),
    (1828, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'First-person and third-person shooting require sustained aiming, movement, and reaction timing; difficulty settings, classes, and progression provide mitigation.'),
    (1830, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Legacy movement, camera, aiming, platforming, and combat controls create substantial burden; difficulty settings and Force powers provide some mitigation.'),
    (1831, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Legacy third-person and first-person combat controls, manual aiming, platforming, and camera behavior create substantial control burden; difficulty settings and Force powers provide some mitigation.'),
    (1833, FALSE, 'Moderate', FALSE, FALSE, TRUE, TRUE, 'Souls-like combat emphasizes dodging, blocking, parrying, positioning, and boss timing; Story Mode, accessibility options, remapping, and game-speed assistance provide strong mitigation.'),
    (1844, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Space-flight combat requires continuous steering, aiming, and target management; digital play avoids physical-toy requirements, while difficulty options and co-op provide mitigation.'),
    (1909, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Primarily turn-based and exploration-focused gameplay with limited reflex demand; progression and forgiving structure provide mitigation.'),
    (1910, FALSE, 'High', FALSE, FALSE, FALSE, FALSE, 'Boxing gameplay depends heavily on rapid reaction timing, pattern recognition, precise dodging, and timed attacks; little meaningful built-in mitigation is available.'),
    (1922, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Third-person shooting creates aiming burden, but built-in targeting assistance, RPG progression, AI support, and easier difficulty provide mitigation.'),
    (1932, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Legacy movement, camera, aiming, and combat controls create substantial burden; modern rerelease conveniences such as rewind and save-state support provide partial mitigation.'),
    (1933, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Legacy movement, camera, aiming, and combat controls create substantial burden; modern rerelease conveniences such as rewind and save-state support provide partial mitigation.'),
    (1934, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Legacy movement, camera, aiming, and combat controls create substantial burden; modern rerelease conveniences such as rewind and save-state support provide partial mitigation.'),
    (1935, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Legacy movement, camera, aiming, and combat controls create substantial burden; modern rerelease conveniences and difficulty options provide partial mitigation.'),
    (1936, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'PSP-era third-person shooting and camera controls create substantial burden; alternate control options, target assistance, and difficulty settings provide partial mitigation.'),
    (1954, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Real-time party RPG combat is comparatively conventional; difficulty settings and AI-controlled party members provide mitigation.'),
    (1955, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional real-time party RPG combat with AI-controlled allies; difficulty settings and progression provide mitigation without creating a major control-risk concern.'),
    (1956, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (1975, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time combat, platforming, aiming, inventory management, and boss encounters create moderate coordination demand; preparation, equipment, building, and progression provide substantial mitigation.'),
    (1984, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Traversal and combat require camera coordination and quick reactions; difficulty settings and automated web-swing assistance reduce burden.'),
    (1985, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Traversal and combat require camera coordination and quick reactions; difficulty settings and automated web-swing systems reduce burden.'),
    (1991, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time action-RPG combat, movement, party management, and exploration create moderate coordination demand; difficulty options and progression provide mitigation.'),
    (2001, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person survival-horror combat, dodging, melee, aiming, and resource management create moderate burden; selectable difficulty and accessibility options provide mitigation.'),
    (2008, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'High-speed driving, flying, and boating require sustained coordination, but assist settings, forgiving progression, and vehicle tuning provide mitigation.'),
    (2022, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (2030, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person survival-horror combat, aiming, stealth, and resource pressure create moderate burden; easier difficulty and progression provide mitigation.'),
    (2031, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Third-person survival-horror combat and resource pressure create aiming and reaction demands; easier difficulty and assistance options provide mitigation.'),
    (2040, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'First-person survival, combat, and resource management add burden; Peaceful mode and optional cooperative play provide strong mitigation.'),
    (2054, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Low-pressure exploration and puzzle structure with minimal reflex demand; no identified major playability-risk category.'),
    (2056, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Platforming, camera behavior, character movement, and directing Trico create substantial control burden despite limited conventional combat pressure; checkpoints and forgiving failure provide mitigation.'),
    (2058, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Turn-based command structure minimizes reflex demand; party composition, formations, progression, and tactical planning provide mitigation.'),
    (2060, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Third-person stealth and combat require aiming, movement, and resource management; lower difficulty, forgiving checkpoints, and stealth provide mitigation.'),
    (2063, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Turn-based combat substantially reduces reflex demand; timing-based attacks add some input burden, but repetition and progression provide mitigation.'),
    (2079, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (2080, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'Legacy controls and camera conventions, but no identified severe control barrier.'),
    (2081, TRUE, 'None', FALSE, FALSE, FALSE, FALSE,
 'Wii version requires Wii MotionPlus-compatible motion controls and Nunchuk; special accessory requirement triggers hard exclusion.'),
    (2099, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting, cover movement, aiming, and quick-time sequences create moderate coordination demand; checkpoints and conventional shooter assistance provide mitigation.'),
    (2100, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (2116, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (2122, FALSE, 'Moderate', FALSE, FALSE, TRUE, TRUE,
 'Souls-like combat emphasizes stamina, dodging, blocking, positioning, and targeted limb attacks; gear progression, implants, and build optimization provide mitigation.'),
    (2123, FALSE, 'Moderate', FALSE, FALSE, TRUE, TRUE,
 'Souls-like combat emphasizes directional parrying, stamina, dodging, positioning, and limb targeting; builds, gear progression, implants, and online support systems provide mitigation.'),
    (2128, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'First-person puzzle and exploration gameplay emphasizes reasoning rather than reflex execution; forgiving structure and low combat pressure provide mitigation.'),
    (2130, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Real-time action-RPG combat uses stance switching, dodging, blocking, and companion management; easier difficulty and progression provide mitigation.'),
    (2136, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Slow exploration-focused narrative structure with limited reflex demand; virtual reality support is optional and does not create an accessory requirement.'),
    (2141, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Narrative adventure structure has low general motor demand, but repeated QTEs and timed action sequences create moderate input-timing burden; checkpoints and forgiving failure provide mitigation.'),
    (2163, FALSE, 'High', TRUE, FALSE, FALSE, FALSE, 'Rhythm-based gameplay depends on rapid timing, repeated precision inputs, and escalating pattern complexity; virtual reality is optional, and little meaningful mitigation removes the core timing burden.'),
    (2181, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Turn-based JRPG structure keeps reflex demand low; music-themed presentation does not make it rhythm-focused. Difficulty selection and party progression provide mitigation.'),
    (2183, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Tactical third-person shooting, aiming, stealth, and inventory systems create moderate burden; difficulty customization, accessibility options, AI teammates, and co-op provide strong mitigation.'),
    (2184, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional third-person tactical-shooter controls; easier difficulty and squad or tactical options provide substantial mitigation.'),
    (2187, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person stealth, aiming, movement, gadgets, and contextual actions create coordination demand; difficulty settings and stealth options provide mitigation.'),
    (2188, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional third-person shooter controls; mission difficulty and cooperative play provide meaningful mitigation.'),
    (2189, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (2194, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person combat, traversal, aiming, climbing, and reaction-based sequences create coordination burden; adjustable difficulty and assistance options provide mitigation.'),
    (2206, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Fast hunting-style action combat requires dodging, aiming, weapon management, and large-enemy tracking; AI allies, progression, equipment, and multiplayer provide mitigation.'),
    (2211, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'High-speed racing and stunt challenges require sustained steering, timing, and reaction input; difficulty and assist systems provide mitigation.'),
    (2238, FALSE, 'High', FALSE, FALSE, FALSE, FALSE, 'Legacy vehicular combat requires simultaneous steering, weapon management, arena awareness, and rapid reactions; little meaningful built-in mitigation is available.'),
    (2242, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person competitive shooting, aiming, movement, and reaction timing create moderate coordination demand; conventional shooter controls and progression provide mitigation.'),
    (2245, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting, climbing, traversal, melee combat, and action sequences create moderate coordination demand; difficulty settings and checkpoints provide mitigation.'),
    (2264, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based tactical structure greatly reduces sustained reflex demand; difficulty settings, squad progression, and deliberate unit control provide mitigation.'),
    (2265, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Turn-based tactical structure greatly reduces reflex demand; deliberate unit control, replayable content, and squad progression provide mitigation.'),
    (2276, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Very fast third-person shooting, boosting, and precision aiming create substantial coordination demand; easier difficulty and aim assistance provide mitigation.'),
    (2299, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Simple combat inputs are offset by legacy movement and lock-on behavior; multiple difficulty levels provide mitigation.'),
    (2305, FALSE, 'High', FALSE, FALSE, FALSE, TRUE, 'Fast first-person melee combat requires sustained movement, aiming, blocking, dodging, and crowd management; difficulty settings, progression, and cooperative play provide mitigation.'),
    (2311, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (2322, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time action combat, stance switching, stealth, and movement create coordination demand; difficulty options and progression provide mitigation.'),
    (2334, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based JRPG combat minimizes reflex demand; party management, progression, and menu-driven systems provide mitigation.'),
    (2335, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based JRPG combat minimizes reflex demand; party management, progression, and conventional menu-driven systems provide mitigation.'),
    (2336, FALSE, 'Moderate', FALSE, TRUE, FALSE, TRUE, 'Arcade shooting requires sustained aiming, movement, and enemy-wave reaction timing; difficulty selection and repeated practice provide mitigation.'),
    (2339, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Real-time melee combat, dodging, sailing, traversal, and survival systems create moderate coordination demand; progression and difficulty adjustments provide mitigation.'),
    (2341, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'High-speed racing requires sustained steering and reaction input; virtual reality is optional, and difficulty or assist settings provide mitigation.'),
    (2356, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting, large enemy groups, movement, and team combat create sustained coordination demand; difficulty settings, AI teammates, and co-op provide mitigation.'),
    (2357, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Turn-based RPG combat keeps reflex demand low; difficulty settings, party building, and progression provide strong mitigation.'),
    (2361, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Fast retro-style first-person combat demands sustained aiming, movement, and enemy tracking; multiple difficulty settings provide mitigation.'),
    (2369, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person action-adventure combat, dodging, platforming, and camera movement create moderate coordination demand; difficulty and progression provide mitigation.'),
    (2373, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (2379, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (2380, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (2381, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (2382, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (2383, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (2384, FALSE, 'None', FALSE, FALSE, FALSE, FALSE,
 'No identified major playability risk under current GAIAS rules.'),
    (2385, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Real-time brawler combat can become hectic and combo-heavy; difficulty settings, healing items, equipment, and progression provide mitigation.'),
    (2396, FALSE, 'None', FALSE, FALSE, FALSE, TRUE, 'Conventional 3D platforming and exploration with forgiving combat; no identified major control-risk category.'),
    (2402, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Fast real-time action combat, dodging, guarding, character switching, and traversal abilities create coordination demand; difficulty settings provide mitigation.'),
    (2403, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Fast action combat and boss encounters require movement and reaction timing; difficulty selection provides meaningful mitigation.'),
    (2404, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE,
 'Fast real-time action combat uses dodging, guarding, character switching, and timing; selectable difficulty provides substantial mitigation.'),
    (2419, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting, aiming, movement, and large enemy groups create moderate coordination demand; difficulty settings, progression, and cooperative play provide mitigation.'),
    (2420, FALSE, 'Moderate', FALSE, FALSE, FALSE, TRUE, 'Third-person shooting, aiming, movement, and large enemy groups create moderate coordination demand; difficulty settings and cooperative play provide mitigation.'),
    (2427, FALSE, 'None', FALSE, FALSE, FALSE, TRUE,
 'Conventional action-adventure controls with some brush-based precision demands; combat, exploration, upgrades, and forgiving progression provide mitigation.')
ON CONFLICT (GameID) DO UPDATE SET
    SpecialAccessoryRequired = EXCLUDED.SpecialAccessoryRequired,
    ControlSchemeRisk = EXCLUDED.ControlSchemeRisk,
    RhythmFlag = EXCLUDED.RhythmFlag,
    SHMUPFlag = EXCLUDED.SHMUPFlag,
    SoulslikeFlag = EXCLUDED.SoulslikeFlag,
    MitigationAvailable = EXCLUDED.MitigationAvailable,
    PlayabilityNotes = EXCLUDED.PlayabilityNotes;